name: hrmadmin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  email_validator: ^2.1.17
  motion_toast: ^2.8.0
  path: ^1.9.0
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1

  flutter: 
    sdk: flutter
  firebase_storage: ^11.6.10
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/image/
  uses-material-design: true

